require 'yaml'
require 'singleton'


require_relative 'coconut/version'
require_relative '../lib/generators/generators'
require_relative 'coconut/null_configuration'
require_relative 'coconut/configuration'
require_relative 'coconut/global'
require_relative 'coconut/config_folder'
require_relative 'coconut/app'
require_relative 'coconut/server'
require_relative 'coconut/cache_service'
require_relative 'coconut/command_interface'
require_relative 'coconut/cli'
